site: manuelmazzuola.dev
url: https://manuelmazzuola.dev
title: manuelmazzuola.dev
description: Manuel Mazzuola's blog
googlewebfonts: Fira+Code:wght@400;500;700
github: 
  username: manuelmazzuola
twitter:
  username: manuelmazzuola
  card: summary
  creator: manuelmazzuola
author:
  twitter: manuelmazzuola
  name: manuelmazzuola
  avatar:
  email: originof@tuta.io
  url: https://manuelmazzuola.dev
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"